### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by SEKalashi** [SEKalashi/furima-28816#9]
フリマアプリのURL | https://furima-28816.herokuapp.com/

Basic認証のIDとパスワード |  ID：Kalashi　パスワード：0079

出品者用のメールアドレスとパスワード | アドレス：test@com　パスワード：aaa111 

購入者用のメールアドレスとパスワード | アドレス：aaa@com　パスワード：bbb222 

購入用カードの番号・期限・セキュリティコード |番号：4242424242424242　期限：12/24　コード：123

**Comment by tec-camp** [comment]
SEKalashinikovさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
○ ログアウトした状態でも、商品詳細ページを閲覧できる
→詳細をクリックすると以下に遷移します
https://gyazo.com/1bcf52cc16512436ab48c3b007960d69

○ クレジットカード決済ができる
→必須項目を入力しても購入することができません
https://gyazo.com/4ef48e4cde2d3c650d6559c6e26d8f78

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by SEKalashinikov** [comment]
未ログインユーザーの商品詳細閲覧を可能にビューファイルを修正
herokuへ公開鍵と秘密鍵を設定し、購入可能に修正

以上を行いました。よろしくお願いします。

**Comment by oooooooba** [comment]
SEKalashinikovさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、

下記2点は必須ではありませんが、余裕があればこちらも修正し、よりクオリティの高いアプリケーションにしてみていただければと思います。

・出品者が出品した商品の「購入画面へ進む」ボタンが表示されている
→出品者自身の商品は購入できないようになっていますが、「購入画面へ進む」ボタンが表示されているので、
出品者には表示されないようにしましょう。

・SoldOutになっている商品は削除ができない
→購入済になっている商品でも、出品者が削除できるようにしましょう。



また、完了要件としてその他の機能には全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
